-- ============================================================
-- Sales Analytics & Automation Platform
-- PostgreSQL Star Schema
-- ============================================================
-- This script creates the analytical star schema used by the
-- Python ETL pipeline and Power BI dashboard.
--
-- Grain of fact_sales:
-- One sales transaction / cleaned source row.
--
-- Date key convention:
-- YYYYMMDD stored as an integer (example: 20261231).
-- ============================================================

-- =========================
-- DIMENSION: DATE
-- =========================

CREATE TABLE IF NOT EXISTS dim_date (
    date_key    INTEGER PRIMARY KEY,
    full_date   DATE NOT NULL,
    day         INTEGER NOT NULL,
    month       INTEGER NOT NULL,
    month_name  VARCHAR(20) NOT NULL,
    quarter     VARCHAR(2) NOT NULL,
    year        INTEGER NOT NULL,
    CONSTRAINT uq_dim_date_full_date UNIQUE (full_date)
);


-- =========================
-- DIMENSION: CUSTOMER
-- =========================

CREATE TABLE IF NOT EXISTS dim_customer (
    customer_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  VARCHAR(50) NOT NULL,
    customer_name VARCHAR(255),
    CONSTRAINT uq_dim_customer_customer_id UNIQUE (customer_id)
);


-- =========================
-- DIMENSION: PRODUCT
-- =========================

CREATE TABLE IF NOT EXISTS dim_product (
    product_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  VARCHAR(50) NOT NULL,
    product_name VARCHAR(255),
    unit_price  NUMERIC(12,2),
    CONSTRAINT uq_dim_product_product_id UNIQUE (product_id)
);


-- =========================
-- DIMENSION: REGION
-- =========================

CREATE TABLE IF NOT EXISTS dim_region (
    region_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_name VARCHAR(100) NOT NULL,
    CONSTRAINT uq_dim_region_region_name UNIQUE (region_name)
);


-- =========================
-- FACT: SALES
-- =========================

CREATE TABLE IF NOT EXISTS fact_sales (
    sales_key    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     VARCHAR(50),
    date_key     INTEGER NOT NULL,
    customer_key INTEGER NOT NULL,
    product_key  INTEGER NOT NULL,
    region_key   INTEGER NOT NULL,
    quantity     INTEGER,
    unit_price   NUMERIC(12,2),
    discount     NUMERIC(5,2),
    sales_amount NUMERIC(14,2),

    CONSTRAINT fk_fact_sales_date
        FOREIGN KEY (date_key)
        REFERENCES dim_date(date_key),

    CONSTRAINT fk_fact_sales_customer
        FOREIGN KEY (customer_key)
        REFERENCES dim_customer(customer_key),

    CONSTRAINT fk_fact_sales_product
        FOREIGN KEY (product_key)
        REFERENCES dim_product(product_key),

    CONSTRAINT fk_fact_sales_region
        FOREIGN KEY (region_key)
        REFERENCES dim_region(region_key)
);


-- ============================================================
-- END OF SCHEMA
-- ============================================================
